### PR TITLE
Security updates for contact page

### PR DESCRIPTION
**Pull request by micahlt**
**🔎 Preview deployment**: https://memphishacks-site.micahlt.repl.co/contact.html

This PR:
- Adds a consistent card-based UI to the contact page
- Adds my bio and contact info
- Switches to JavaScript-based contact info (essentially it `fetches` a separate `contactinfo.json` file and then uses that to provide info to the `contact.html` page with `contact.js` - this will improve security and prevent bots from scraping the page for info

### CODE REVIEW

**Comment by micahlt** [comment]
cc @philip-hub

**Comment by micahlt** [comment]
@philip-hub hold up, this isn't working - looks like it's an issue with the domain not being on GitHub.  We're gonna have to either roll back this PR or add `memphishack.com` as an _actual_ domain rather than a redirect.  At the moment the contact page just gives 404 errors when trying to fetch the contact info list.

**Comment by philip-hub** [comment]
Yes I see what you mean, hopefully soon I can set up the domain, but I love the cards. For the time being, I will revert edit the page to have the contact info back on it.

**Comment by micahlt** [comment]
👍 If I can help in any way just let me know.

**Pull request merged**
